# Generated by Django 3.2.5 on 2022-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sampleimage', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
